name       : libbdplus
version    : 0.1.2
release    : 1
source     :
    - ftp://ftp.videolan.org/pub/videolan/libbdplus/0.1.2/libbdplus-0.1.2.tar.bz2 : a631cae3cd34bf054db040b64edbfc8430936e762eb433b1789358ac3d3dc80a
license    : LGPL-2.0
component  : multimedia.codecs
summary    : Library for handling the BD+ protection scheme on bluray discs.
description: |
    Library for handling the BD+ protection scheme on bluray discs.
builddeps  :
    - pkgconfig(libaacs)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
